name: Google Cloud Run CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_JSON }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Run
        run: |
            gcloud auth activate-service-account --key-file=${{ secrets.GCP_KEY_JSON }}
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
            gcloud config set run/region us-central1
            chmod +x ./continuous_deploy.sh
            ./continuous_deploy.sh
