name: Google Cloud Run CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_JSON }}
          export_default_credentials: true

      - name: Authenticate gcloud account
        run: |
          echo "${{ secrets.GCP_KEY_JSON_BASE64 }}" | base64 --decode > "${{ runner.temp }}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${{ runner.temp }}/gcloud-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      - name: Deploy to Google Cloud Run
        run: |
          chmod +x ./continuous_deploy.sh
          ./continuous_deploy.sh
